### ISSUE TITLE
Redundant usage of "|| true"

### ISSUE THREAD

**Issue by Lolimpo** [soul-catcher/mypy-gitlab-code-quality#1]
In my oppinion it's better to use more obvious gitlab flag `allow_failure`, rather than "faking" success at the script stage:
```
codequality:
  script:
    - pip install mypy mypy-gitlab-code-quality
    - mypy program.py --no-error-summary > mypy-out.txt
    - PYTHONHASHSEED=0 mypy-gitlab-code-quality < mypy-out.txt > codequality.json
  artifacts:
    when: always
    reports:
      codequality: codequality.json
  allow_failure: true
```
Also I think that it's more representable for the developer. As with always "green" pipelines you could miss important reports, even if you have some serious typing issues. With that flag your pipeline won't be failed and other jobs won't be blocked, but developer could pay more attention to it.
