### ISSUE TITLE
How to de-duplicate mypy jobs

### ISSUE THREAD

**Issue by Kilo59** [soul-catcher/mypy-gitlab-code-quality#51]
I want to use this package as intended to upload gitlab codequality artifacts, but I also want to block merge requests (fail a job) if there are mypy errors.

Is there a recommended way to do this without having to run the mypy check multiple times?

I understand that I could just allow the codequality run of mypy to fail, but that would prevent the upload of the report.

**Comment by ssolodskih** [comment]
```
 - | 
    set +e
    mypy --config mypy.toml --no-pretty --no-incremental $FILES_TO_CHECK > mypy-out.txt
    MYPY_EXIT=$?
 - mypy-gitlab-code-quality < mypy-out.txt > ${CI_PROJECT_DIR}/mypy-codequality.json
 - exit $MYPY_EXIT
```

Something like this will do. You can replace $FILES_TO_CHECK with whatever path you need

**Comment by Kilo59** [comment]
@ssolodskih Thank you. This is what I've ended up using. 
Note: my `pyproject.toml` file defines what files for mypy to check.

```yaml
Type Checking:
  extends: .base_poetry # installs dependencies
  script:
    - |
      set +e
      mypy --no-pretty --warn-unused-ignores --no-incremental > mypy-out.txt
      MYPY_EXIT=$?
    - cat mypy-out.txt
    - mypy-gitlab-code-quality < mypy-out.txt > codequality.json
    - exit $MYPY_EXIT
  artifacts:
    when: always
    reports:
      codequality: codequality.json
```

I do wish mypy could generate a `json` report + log STDOUT in a single run. I do like being able to see the `--pretty` output in my CI but that's a minor gripe.
